const { Row } = Liteframe;
import Modal from '../../shared/Modal';
import { Button } from '../../utils/Button';
import { IconButton, IonIcon } from '../../utils/Icon';
import { PurchaseReceipt } from './PurchaseReceipt';

/** Format date to dd/mm/yyyy for receipt display. */
function formatDateDDMMYYYY(value) {
  if (value == null || value === '') return '';
  try {
    const date = new Date(value);
    if (isNaN(date.getTime())) return '';
    const d = String(date.getDate()).padStart(2, '0');
    const m = String(date.getMonth() + 1).padStart(2, '0');
    const y = date.getFullYear();
    return `${d}/${m}/${y}`;
  } catch (e) {
    return '';
  }
}

/**
 * Build receiptData shape expected by PurchaseReceipt (former layout) from API receipt + settings.
 */
export function buildReceiptData(receipt, settings) {
  const meta = receipt.order_meta || {};
  const payment = receipt.order_payment || {};
  const companyName = (settings.company_name || '').trim() || 'Company';
  const paymentStatus = payment && payment.remaining_balance > 0.01 ? 'PARTIAL' : (meta.payment_status || 'PAID');
  const withholdPct = meta.withhold_percentage != null ? Number(meta.withhold_percentage) : null;
  const withholdInfo = withholdPct != null && (meta.withhold_amount || 0) > 0
    ? `${withholdPct}% withheld`
    : 'N/A';

  const receiptData = {
    receiptNo: receipt.receipt_no ?? '',
    dateIssued: formatDateDDMMYYYY(meta.order_date),
    fromCompany: {
      businessName: companyName,
      address: (settings.company_address || '').trim(),
      phone: (settings.company_phone || '').trim(),
      email: (settings.company_email || '').trim(),
      taxId: (settings.company_tin || '').trim(),
    },
    toSupplier: {
      supplierName: meta.supplier_name || `ID: ${meta.supplier_id || '—'}`,
      address: meta.supplier_address || '',
      contact: meta.supplier_contact || '',
      contactPerson: meta.supplier_contact || '',
      email: meta.supplier_email || '',
      taxId: meta.supplier_tin || 'N/A',
    },
    orderDetails: {
      purchaseDate: formatDateDDMMYYYY(meta.order_date),
      paymentMode: (meta.payment_mode || '').replace(/\b\w/g, (c) => c.toUpperCase()),
      withholdTaxInfo: withholdInfo,
      status: `${paymentStatus} COMPLETED`,
      referencePO: (meta.reference_po || receipt.receipt_no) ?? '',
    },
    items: (receipt.order_items || []).map((it) => ({
      productCode: it.product_code ?? '',
      description: it.product_name || `Product #${it.product_id}`,
      batchNo: it.batch_number ?? '',
      expiryDate: formatDateDDMMYYYY(it.expiry_date),
      qty: it.quantity ?? 0,
      unitPrice: it.unit_price,
      totalAmount: it.total_price,
    })),
    summary: {
      subtotal: meta.subtotal ?? 0,
      taxableAmount: meta.subtotal ?? meta.net_amount ?? 0,
      withholdTaxPercentage: withholdPct ?? 0,
      withholdTaxAmount: meta.withhold_amount ?? 0,
      vatPercentage: meta.vat_percentage ?? null,
      vatAmount: meta.vat_amount ?? null,
      totalAmountDue: meta.net_amount ?? 0,
      amountPaid: payment.initial_payment_amount ?? 0,
      remainingBalance: payment.remaining_balance ?? 0,
    },
    notesAndTerms: {
      title: 'Important Notes & Terms:',
      list: [
        'This receipt is valid only for the items and amounts stated above.',
        'Goods once sold are subject to our return policy.',
      ],
    },
    footerInfo: {
      thankYouMessage: 'Thank you for your business.',
      companyLine1: companyName,
      emailLink: (settings.company_email || '').trim(),
      webLink: (settings.company_website || '').trim() || '#',
      systemGeneratedMessage: 'This is a computer-generated receipt.',
      softwareCredit: 'Generated by PharmaSuit — Pharmaceutical Wholesale Management system by MasaTech',
    },
    watermarkText: 'PROCESSED',
  };

  return receiptData;
}

/**
 * Opens the purchase receipt modal. Fetches receipt by orderId and company settings, then renders the former receipt layout.
 * @param {Object} options - { orderId: number }
 */
export async function openReceiptModal(options) {
  const { orderId } = options || {};
  if (!orderId) return;

  let receipt = null;
  let settings = {};
  try {
    const [receiptResult, settingsResult] = await Promise.all([
      window.ipcRenderer.invoke('purchase:get-order-receipt', orderId),
      window.ipcRenderer.invoke('settings:get').catch(() => ({ success: false, settings: {} })),
    ]);
    if (receiptResult && receiptResult.success && receiptResult.receipt) receipt = receiptResult.receipt;
    if (settingsResult && settingsResult.success && settingsResult.settings) settings = settingsResult.settings;
  } catch (e) {
    console.error('ReceiptModal fetch error:', e);
  }

  if (!receipt) {
    if (typeof window !== 'undefined' && window.alert) window.alert('Receipt not found.');
    return;
  }

  Modal({}, (delegator, handleClose) => {
    return ReceiptModalContent({ receipt, settings, handleClose, delegator });
  });
}

function ReceiptModalContent({ receipt, settings, handleClose, delegator }) {
  const receiptData = buildReceiptData(receipt, settings);

  const handlePrint = () => {
    document.title = `Receipt ${receipt.receipt_no || ''}`;
    window.print();
  };

  const receiptContainer = PurchaseReceipt(receiptData, delegator, false);

  const printWrapper = document.createElement('div');
  printWrapper.id = 'receipt-print-area';
  printWrapper.className = 'receipt-print-area';
  printWrapper.appendChild(receiptContainer);

  return Row(
    {
      class: 'flex flex-col w-full max-w-[210mm] bg-white rounded-xl shadow-xl overflow-hidden max-h-[90vh]',
      delegator,
    },
    [
      Row(
        {
          class: 'flex items-center justify-between px-4 py-3 border-b border-gray-200 bg-gray-50 flex-shrink-0',
        },
        [
          Row({ class: 'flex items-center gap-2' }, [
            IonIcon({ name: 'receipt-outline', class: 'text-2xl text-indigo-600' }),
            Row({ class: 'text-base font-semibold text-gray-900' }, 'Purchase Receipt'),
          ]),
          Row({ class: 'flex items-center gap-2' }, [
            Button({ variant: 'outline', onClick: handlePrint, delegator, class: 'text-sm py-1.5 px-3' }, [
              IonIcon({ name: 'print-outline', class: 'text-lg mr-1' }),
              'Print',
            ]),
            IconButton({ onClick: handleClose, delegator, class: 'text-gray-500 hover:text-gray-700' }, [
              IonIcon({ name: 'close-outline', class: 'text-xl' }),
            ]),
          ]),
        ]
      ),
      Row({ class: 'p-4 overflow-y-auto flex-1 min-h-0' }, [printWrapper]),
    ]
  );
}
