GRANT USAGE ON SCHEMA public TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.account_ledger TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.bin_cards TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.borrow_from_inventories TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.borrow_from_returns TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.borrow_to_inventories TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.borrow_to_returns TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.cash_loans_payable TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.cash_loans_receivable TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.categories TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.chart_of_accounts TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.customers TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.deposits TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.expenses TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.fiscal_years TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.inventories TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.knex_migrations TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.knex_migrations_lock TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.licenses TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.platform_admins TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.products TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.purchase_hold_orders TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.purchase_order_items TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.purchase_orders TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.purchase_payments TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.purchase_receipts TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.role_rules TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.roles TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.rules TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.sales_hold_orders TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.sales_order_items TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.sales_orders TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.sales_payments TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.system_settings TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tenants TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.test_items TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.units TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.user_roles TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.user_rules TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.users TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.withhold_payable_settlement_items TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.withhold_payable_settlements TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.withhold_receivable_settlement_items TO masatetw_pharmasuit;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.withhold_receivable_settlements TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.account_ledger_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.bin_cards_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.borrow_from_inventories_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.borrow_returns_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.borrow_to_inventories_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.borrow_to_returns_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.cash_loans_payable_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.cash_loans_receivable_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.categories_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.chart_of_accounts_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.customers_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.deposits_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.expenses_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.fiscal_years_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.inventories_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.knex_migrations_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.knex_migrations_lock_index_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.licenses_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.platform_admins_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.products_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.purchase_hold_orders_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.purchase_order_items_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.purchase_orders_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.purchase_payments_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.purchase_receipts_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.roles_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.rules_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.sales_hold_orders_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.sales_order_items_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.sales_orders_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.sales_payments_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.system_settings_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.tenants_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.test_items_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.units_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.users_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.withhold_payable_settlement_items_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.withhold_payable_settlements_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.withhold_receivable_settlement_items_id_seq TO masatetw_pharmasuit;
GRANT USAGE, SELECT ON SEQUENCE public.withhold_receivable_settlements_id_seq TO masatetw_pharmasuit;
