directories:
  output: release/${version}
  buildResources: build
$schema: https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json
appId: com.masatech.pharmasuitlan
asar: true
productName: PharmaSuitLAN
icon: build/icon.png
files:
  - filter:
      - dist
      - dist-electron
extraResources:
  - from: ../api
    to: api
    filter:
      - package.json
      - package-lock.json
      - .env
      - src/**/*
      - db/**/*
      - node_modules/**/*
mac:
  target:
    - dmg
  artifactName: ${productName}-Mac-${version}-Installer.${ext}
win:
  target:
    - target: nsis
      arch:
        - x64
  artifactName: ${productName}-Windows-${version}-Setup.${ext}
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
linux:
  target:
    - AppImage
  artifactName: ${productName}-Linux-${version}.${ext}
electronVersion: 30.5.1
