name: Deploy to cPanel

on:
  push:
    branches:
      - cloud-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Sync files via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SERVER_HOST }}
        username: mltplcpi
        password: ${{ secrets.SERVER_PASSWORD }}
        server-dir: "network-desktop-app/api/" # Target path on your cPanel
        local-dir: "api/" # Local folder to sync
        exclude: |
          **/.git*
          **/node_modules/**
          **/*.sqlite

    - name: Execute Server Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: mltplcpi
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 7822 # Keeps the A2 port configuration fallback
        script: |
          source /home/mltplcpi/nodevenv/network-desktop-app/api/20/bin/activate && cd /home/mltplcpi/network-desktop-app/api
          npm install --production
          npm run migrate
          mkdir -p tmp
          touch tmp/restart.txt